# Generated by Django 3.1.3 on 2020-11-19 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addstudent',
            old_name='comment',
            new_name='password',
        ),
        migrations.AddField(
            model_name='addstudent',
            name='address',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addstudent',
            name='phoneno',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addstudent',
            name='std',
            field=models.CharField(default='', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addstudent',
            name='studentid',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
